### ISSUE TITLE
关于modules文件夹中的actions.js，mutations.js文件。

### ISSUE THREAD

**Issue by jw0903** [XuXiaoGH/vuex-test#1]
这两个文件是不是就只是一个例子，在整个程序中不起作用？起作用的只是todo文件夹还有login.js？

**Comment by XuXiaoGH** [comment]
对呀，外层的这两个文件没有使用，因为为了演示复杂点的module模式，所以用todo文件夹里的了。
外面的actions.js 和 mutation.js 其实用起来也和里面一样用，当项目比较简单的时候用，然后只需要在 store.js 去引入即可。

**Comment by jw0903** [comment]
还有一个就是为什么要单独设置一个mutations_type.js文件，不是很懂？

**Comment by XuXiaoGH** [comment]
是这样的。
如果 `vuex` 的功能方法少，就可以像 `login.js` 一样直接写在一个文件里。
但是如果功能方法多，那就要分成 `actions.js`  `mutation.js`，但是这两个文件里都需要 `type`，总不能写在
 `actions` 里，然后 `mutations` 去引入 `actions` 吧。

所以把 `type` 单独提出来，然后 `actions` ，`mutations` 分别去自己去引入就行了。

其实就是类似一个通用配置。

**Comment by jw0903** [comment]
嗯嗯，懂了，谢谢

发自我的 iPhone
